using System;
using System.IO;
using static MatrixMultiply.Exceptions;

namespace MatrixMultiply
{
    class Program
    {
        static void Main(string[] args)
        {

            Measurements.PrintMeasurements((matrix1, matrix2) => matrix1.ParallelMultiply(matrix2));
            Measurements.PrintMeasurements((matrix1, matrix2) => matrix1.Multiply(matrix2));

            if (args.Length != 3)
            {
                Console.WriteLine("Expected to have 3 arguments");
                return;
            }

            try
            {
                var matrix1 = new Matrix(FileOperations.ReadMatrix(args[0]));
                var matrix2 = new Matrix(FileOperations.ReadMatrix(args[1]));
                var result = matrix1.ParallelMultiply(matrix2);
                FileOperations.WriteMatrix(args[2], result);
            }
            catch (FileNotFoundException e)
            {
                Console.WriteLine(e.Message);
            }
            catch (EmptyFileException e)
            {
                Console.WriteLine(e.Message);
            }
            catch (FormatException e)
            {
                Console.WriteLine(e.Message);
            }
            catch (InvalidMatrixFormatException e)
            {
                Console.WriteLine(e.Message);
            }
        }
    }
}
